name: learn actions on pull request
on:
  pull_request:
    types:
      - closed
jobs:
  closing:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Close
        run: echo 'Your PR is closed'
